- name: Create a temp dir
  tempfile:
    state: directory
    prefix: build
  register: temp_output

- name: Set tmp_path
  set_fact:
    tmp_path: "{{ temp_output.path }}"

- name: Clone nginx openshift router repository
  git:
    repo: 'https://github.com/nginxinc/nginx-openshift-router'
    dest: "{{ tmp_path }}/nginx-openshift-router"
    version: master
  ignore_errors: true

- name: Copy NGINX license files to repository
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ tmp_path }}/nginx-openshift-router/src/nginx-plus/{{ item }}"
  with_items:
    - nginx-repo.crt
    - nginx-repo.key

- name: Build NGINX Plus docker image
  command: docker build -t nginx-plus-openshift-router:0.2 .
  args:
    chdir: "{{ tmp_path }}/nginx-openshift-router/src/nginx-plus"
  changed_when: false

- name: Get admin token
  command: oc whoami -t
  register: admintoken
  changed_when: false

- name: extract registry certificate
  command: oc extract -n default secrets/registry-certificates --keys=registry.crt
  args:
    chdir: "{{ tmp_path }}"
  changed_when: false

- name: Get registry url
  command: oc get routes -n default docker-registry -o jsonpath='{.spec.host}'
  register: registry
  changed_when: false

- name: create docker certs directory for registry
  file:
    path: /etc/containers/certs.d/{{ registry.stdout }}
    state: directory

- name: copy docker-registry certificate to certs directory
  copy:
    src: "{{ tmp_path }}/registry.crt"
    dest: /etc/containers/certs.d/{{ registry.stdout }}/registry.crt

- name: Logon to OpenShift docker registry
  command: "docker login -p {{ admintoken.stdout }} -u unused {{ registry.stdout }}"
  changed_when: false

- name: Tag NGINX Plus docker image
  command: "docker tag nginx-plus-openshift-router:0.2 {{ registry.stdout }}/openshift/nginx-plus-openshift-router:0.2"
  args:
    chdir: "{{ tmp_path }}/nginx-openshift-router/src/nginx-plus"
  changed_when: false

- name: Push NGINX Plus docker image
  command: "docker push {{ registry.stdout }}/openshift/nginx-plus-openshift-router:0.2"
  args:
    chdir: "{{ tmp_path }}/nginx-openshift-router/src/nginx-plus"
  changed_when: false

- name: Backup default Router configuration
  shell: "oc get -o yaml service/router dc/router clusterrolebinding/router-router-role serviceaccount/router > default-router-backup.yml"
  args:
    executable: /bin/bash
    chdir: $HOME
  changed_when: false

- name: Delete Router
  command: "oc delete -f $HOME/default-router-backup.yml"
  changed_when: false

- name: Deploy NGINX Plus router
  command: "oc adm router router --images={{ registry.stdout }}/openshift/nginx-plus-openshift-router:0.2 --type=''"
  changed_when: false

- name: Remove the temp directory
  file:
    path: "{{ tmp_path }}"
    state: absent